version: "3.9"

services:
  backend:
    container_name: hackron-backend
    build:
      context: .
      dockerfile: docker/hackron-backend.dockerfile
    env_file:
      - apps/server/.env
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - hackron-net

  frontend:
    container_name: hackron-frontend
    build:
      context: .
      dockerfile: docker/web.dockerfile
    env_file:
      - apps/web/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hackron-net

networks:
  hackron-net:
    driver: bridge